name: CI

on: push

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -r win-x64

      # Uncomment to enable test builds. Works in concert with the `Deploy 360Test` Scheduled Task on 360API.gordon.edu VM
      # - name: Upload Test Build Artifact
      #   uses: actions/upload-artifact@v2.2.2
      #   if: ${{ github.refs != 'refs/heads/develop' && github.refs != 'refs/heads/master' }}
      #   with:
      #       name: build-Test
      #       path: ${{ github.workspace }}\Gordon360\bin\app.publish\ci
      #       if-no-files-found: warn

      - name: Upload Train Build Artifact
        uses: actions/upload-artifact@v2.2.2
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          name: build-Train
          path: ${{ github.workspace }}\Gordon360\bin\app.publish\ci
          if-no-files-found: error

      - name: Upload Prod Build Artifact
        uses: actions/upload-artifact@v2.2.2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: build-Prod
          path: ${{ github.workspace }}\Gordon360\bin\app.publish\ci
          if-no-files-found: error
