name: CI

on: push

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
